### ISSUE TITLE
rbe_autoconfig with create_java_configs=False failed in verify

### ISSUE THREAD

**Issue by lizan** [bazelbuild/bazel-toolchains#649]
I recently dropped JDK from our RBE toolchain image, so I tried to generate config without java_home (or use remote_jdk) though it fails in verification:

I got some workaround:
https://github.com/bazelbuild/bazel-toolchains/compare/master...lizan:java_home_check_fix?expand=1 though obviously this is not enough to keep existing configs in versions.bzl.

```
ERROR: /home/lizan/github/lizan/envoy/build/WORKSPACE:17:1: Traceback (most recent call last):
        File "/home/lizan/github/lizan/envoy/build/WORKSPACE", line 17
                envoy_dependency_imports()
        File "/home/lizan/github/lizan/envoy/build/bazel/dependency_imports.bzl", line 12, in envoy_dependency_imports
                rbe_toolchains_config()
        File "/home/lizan/.cache/bazel/_bazel_lizan/935de5c3a9ad4318c27353ce3b82b735/external/envoy/bazel/toolchains/rbe_toolchains_config.bzl", line 74, in rbe_toolchains_config
                _envoy_rbe_toolchain("rbe_ubuntu_clang", _CLANG_ENV, "cla...")
        File "/home/lizan/.cache/bazel/_bazel_lizan/935de5c3a9ad4318c27353ce3b82b735/external/envoy/bazel/toolchains/rbe_toolchains_config.bzl", line 47, in _envoy_rbe_toolchain
                rbe_autoconfig(name = (name + "_gen"), export_con..., <8 more arguments>)
        File "/home/lizan/.cache/bazel/_bazel_lizan/935de5c3a9ad4318c27353ce3b82b735/external/bazel_toolchains/rules/rbe_repo.bzl", line 915, in rbe_autoconfig
                validate_toolchain_config_suite_spec(name, toolchain_config_suite_spec)
        File "/home/lizan/.cache/bazel/_bazel_lizan/935de5c3a9ad4318c27353ce3b82b735/external/bazel_toolchains/rules/rbe_repo/toolchain_config_suite_spec.bzl", line 123, in validate_toolchain_config_suite_spec
                _validate_toolchain_config_suite_autogen_spec(name, toolchain_config_suite_spec)
        File "/home/lizan/.cache/bazel/_bazel_lizan/935de5c3a9ad4318c27353ce3b82b735/external/bazel_toolchains/rules/rbe_repo/toolchain_config_suite_spec.bzl", line 164, in _validate_toolchain_config_suite_autogen_spec
                _validate_default_toolchain_config_spec(name, toolchain_config_suite_spec)
        File "/home/lizan/.cache/bazel/_bazel_lizan/935de5c3a9ad4318c27353ce3b82b735/external/bazel_toolchains/rules/rbe_repo/toolchain_config_suite_spec.bzl", line 178, in _validate_default_toolchain_config_spec
                _validate_config_version_spec(name, toolchain_config_suite_spec[...)
        File "/home/lizan/.cache/bazel/_bazel_lizan/935de5c3a9ad4318c27353ce3b82b735/external/bazel_toolchains/rules/rbe_repo/toolchain_config_suite_spec.bzl", line 278, in _validate_config_version_spec
                _check_type(name = name, expected_type = "stri...", <2 more arguments>)
        File "/home/lizan/.cache/bazel/_bazel_lizan/935de5c3a9ad4318c27353ce3b82b735/external/bazel_toolchains/rules/rbe_repo/toolchain_config_suite_spec.bzl", line 472, in _check_type
                fail("{name} has an invalid toolchain...))
rbe_ubuntu_clang_gen has an invalid toolchain_config_suite_spec["toolchain_config_suite_autogen_spec"]. It declares 'struct(config_repos = [], create_cc_configs = True, create_java_configs = False, env = {"BAZEL_COMPILER": "clang", "BAZEL_LINKLIBS": "-l%:libstdc++.a", "BAZEL_LINKOPTS": "-lm:-static-libgcc:-fuse-ld=lld", "BAZEL_USE_LLVM_NATIVE_COVERAGE": "1", "GCOV": "llvm-profdata", "CC": "clang", "CXX": "clang++", "PATH": "/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/llvm-8/bin"}, java_home = None, name = "clang")', that is not a valid config_version_spec as has a java_home that is not a string. Expected 'string' but got 'NoneType'
```

**Comment by nlopezgi** [comment]
Hi @lizan,
Thanks for opening this issue. I was able to repro your issue and will be sending a fix shortly.

**Comment by lizan** [comment]
@nlopezgi Thanks for quick response! I'll try your PR.
